/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package hu.vizespalack.spring.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-15T17:15:26.129Z")

@Api(value = "register", description = "the register API")
@RequestMapping(value = "/v2")
public interface RegisterApi {

    @ApiOperation(value = "request for free space", nickname = "requestFreeTime", notes = "", response = Integer.class, tags = {"register",})
    @ApiResponses(value = {
        @ApiResponse(code = 201, message = "Created", response = Integer.class),
        @ApiResponse(code = 204, message = "No content")})
    @RequestMapping(value = "/register/{workerId}",
        produces = {"application/json"},
        method = RequestMethod.POST)
    ResponseEntity<Integer> requestFreeTime(@ApiParam(value = "ID of the user who the request came from", required = true) @PathVariable("workerId") String workerId);

}
