/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-06-15T17:15:26.129Z")

@Api(value = "entry", description = "the entry API")
@RequestMapping(value = "/v2")
public interface EntryApi {

    @ApiOperation(value = "returns yes/no", nickname = "returnPermission", notes = "", tags = {"entry",})
    @ApiResponses(value = {
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 403, message = "Forbidden")})
    @RequestMapping(value = "/entry/{workerId}",
        method = RequestMethod.PUT)
    ResponseEntity<Void> returnPermission(@ApiParam(value = "ID of the user who the request came from", required = true) @PathVariable("workerId") String workerId);

}
